exclude:			[generateSiteOnBranch.sh]

# Dependencies
markdown:            kramdown
kramdown:
  input:             GFM
  syntax_highlighter: rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Code Craftsman
tagline:             'Software craftsmanship and iOS development'
description:         'This is my personal blog where I talk about software.'
domain_name:         code-craftsman.fr
url:                 http://code-craftsman.fr
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Sébastien Duperron
  twitter:           https://twitter.com/liquidseb
  github:            https://github.com/liquidsoul
  linkedin:          https://fr.linkedin.com/in/sebastienduperron
  email:             contact@code-craftsman.fr

# Disqus
disqus_shortname:    codecraftsmanfr

# Custom vars
version:             1.0.0
